### ISSUE TITLE
`appendVDom` need real dom

### ISSUE THREAD

**Issue by artemave** [featurist/hyperdom#101]
This code

```javascript
hyperdom.appendVDom(h('div'), {render: () => 'hello'})
```

Fails with

```
     ReferenceError: window is not defined
      at new Mount (node_modules/hyperdom/mount.js:10:44)
      at start (node_modules/hyperdom/rendering.js:64:15)
      at startAttachment (node_modules/hyperdom/rendering.js:56:12)
      at Object.exports.appendVDom (node_modules/hyperdom/rendering.js:34:10)
      at Context.<anonymous> (test/hyperdomIntegrationSpec.js:44:14)
```

Looks as if deep down hyperdom assumes there are real `window` and `document` available.

**Comment by dereke** [comment]
I think you can pass in window as an option. Then use the global module to get a window
